

#ifndef AUDIO_CUSTOM_EXP_H
#define AUDIO_CUSTOM_EXP_H

#include "Audio_Customization_Common.h"


#undef  ENABLE_AUDIO_COMPENSATION_FILTER
#undef  ENABLE_AUDIO_DRC_SPEAKER
#undef  ENABLE_HEADPHONE_COMPENSATION_FILTER
#undef  ENABLE_AUDIO_SW_STEREO_TO_MONO
#undef  ENABLE_HIGH_SAMPLERATE_RECORD

#endif
